///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace SourceControl_Test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the SourceControl_TestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("adb932d3-fd98-4b52-80f3-cf52188d1b6d")]
    public partial class SourceControl_TestRepository : RepoGenBaseFolder
    {
        static SourceControl_TestRepository instance = new SourceControl_TestRepository();

        /// <summary>
        /// Gets the singleton class instance representing the SourceControl_TestRepository element repository.
        /// </summary>
        [RepositoryFolder("adb932d3-fd98-4b52-80f3-cf52188d1b6d")]
        public static SourceControl_TestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public SourceControl_TestRepository() 
            : base("SourceControl_TestRepository", "/", null, 0, false, "adb932d3-fd98-4b52-80f3-cf52188d1b6d", ".\\RepositoryImages\\SourceControl_TestRepositoryadb932d3.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("adb932d3-fd98-4b52-80f3-cf52188d1b6d")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class SourceControl_TestRepositoryFolders
    {
    }
#pragma warning restore 0436
}
